spring:
  application:
    name: auth
  cloud:
    config:
      enabled: false
server:
  port: ${PORT}
jwt:
  secret: MiAVzqUXy5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpP
  expiration: 86400
application:
  config:
    users-url: https://budgetwise-users-production.up.railway.app/api/users
